[Add] Add IncludedNoteModel and IncludedNoteModelTest
it-kmitl-2018/group3-backend pull request #17
Opened 2018-02-25 10:08 UTC by chin8628

2018-02-25 13:54 UTC, champillon requested changes
ฝากชี้แจงหน่อยจร้าาาาาา

2018-02-25 13:54 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group3/model/GreetingModel.java
>  public class GreetingModel {
ไมไม่ลบทิ้งไปเลยหล่ะ?

2018-02-25 13:54 UTC, champillon commented on src/test/java/th/ac/kmitl/it/soa/group3/model/exchangeddocument/IncludedNoteModelTest.java
> +
ทำไมมีเว้นวรรทัดตรงนี้หล่ะ

2018-02-25 14:09 UTC, chin8628 commented on src/main/java/th/ac/kmitl/it/soa/group3/model/GreetingModel.java
>  public class GreetingModel {
ส่วนของ controller ยังไม่ได้พัฒนาต่อเป็นของใช้จริงครับ เลยมีส่วนที่เรียกใช้งาน GreetingModel อยู่ เลยไม่สามารถลบได้ครับ เดี๋ยวส่วนนี้ผมขอลบหลังจากมีการทำส่วน Controller เพิ่มเติมนะครับ

2018-02-25 14:10 UTC, chin8628 commented on src/test/java/th/ac/kmitl/it/soa/group3/model/exchangeddocument/IncludedNoteModelTest.java
> +
แก้ไขแล้วครับ ขอบคุณครับ

2018-02-25 14:11 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group3/model/GreetingModel.java
>  public class GreetingModel {
เค

2018-02-25 14:12 UTC, champillon approved these changes
แจ่มแล้ววววววว

2018-02-27 15:13 UTC, chin8628 commented
@champillon พี่แชมป์ครับ รบกวนอันนี้ด้วยครับ เห็นว่าผ่านมาสองวันแล้วไม่มีคน approve ต่อครับ ขอบคุณครับ

2018-02-27 16:31 UTC, champillon commented
@chin8628 พรุ่งนี้เช้า merge ให้นะ อันไหนนานเกิน 2 วัน approve เดียวก็พอ

2018-02-28 02:24 UTC, merged

2018-02-28 02:26 UTC, champillon commented
คะแนนครับ 2.75 คะแนน x 2 Promotion => 5.5 คะแนน
5.1 การ design เป็น components เพื่อทำให้คนอื่นทำงานร่วมกันต่อได้ง่าย => 1 คะแนน
5.2 คุณภาพของการตั้งชื่อตัวแปร, ฟังก์ชั่น และความเรียบร้อยของ code => 0.25 คะแนน ( code น้อยไปหน่อย)
5.3 ความยากเชิงเทคนิคที่นำมาประยุกต์ใช้ เช่น แปลง XML Schema เป็น Java code => 0 คะแนน
5.4 รายละเอียดการตั้งชื่อใน PR name และ commit log รวมทั้งรายละเอียดที่บรรยายใน issue ของ PR นั้นๆ => 1 คะแนน
5.5 ความสอดคล้องกันกับ PR อื่นๆของทีม ที่ทำงานร่วมกันได้ดี => 0.5 คะแนน (ไม่มี test หักหน่อยแล้วกัน เพื่อใช้ยาก)

2018-02-28 03:56 UTC, chin8628 commented
@champillon มันมีเทสนะครับ `IncludedNoteModelTest.java`

2018-02-28 03:56 UTC, champillon commented
@chin8628 พิมผิด test นิดนุงเอง