[Add] Add the PhoneUniversalModel
it-kmitl-2018/group3-backend pull request #21
Opened 2018-02-25 11:19 UTC by chin8628

It's the Telephone Universal Communication model from page 13.

2018-02-25 13:57 UTC, champillon requested changes
ฝากชี้แจงด้วยจร้าาาา

2018-02-25 13:57 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group3/model/supplychaintradetransaction/TelephoneUniversalCommunicationModel.java
> +    public TelephoneUniversalCommunicationModel(String phoneNumber) {
แล้วไมอันนี้ไม่ Fluent (Builder) หล่ะ

2018-02-25 13:57 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group3/model/supplychaintradetransaction/TelephoneUniversalCommunicationModel.java
> +public class TelephoneUniversalCommunicationModel {
ชื่อ Class ยาวไปเป่า เราแนะนำให้มี zone นึง ไว้ binding ชื่อที่เราใช้ กับชื่อของ field ของ ETDA ไม่งั้น ชื่อ field ของ ETDA มันจะยาวและทำให้ code รกมาก

2018-02-25 14:08 UTC, chin8628 commented on src/main/java/th/ac/kmitl/it/soa/group3/model/supplychaintradetransaction/TelephoneUniversalCommunicationModel.java
> +    public TelephoneUniversalCommunicationModel(String phoneNumber) {
พูดตรง ๆ เลยนะครับ 5555 อันนี้อยากลองใจพี่ครับ คือ ผมไม่ชัวร์ว่าควรใช้ builder ดีไหม เพราะ model นี้มีแค่ property เดียวครับ เลยลองไม่ใช้ดู และจะใช้ build กับที่มีหลาย properties ครับ

2018-02-25 14:09 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group3/model/supplychaintradetransaction/TelephoneUniversalCommunicationModel.java
> +    public TelephoneUniversalCommunicationModel(String phoneNumber) {
เราอยากให้เป็น pattern เดียวกันอ่ะ จะ Builder ก็ Builder ให้หมดเลยยยยยยยย

2018-02-25 14:10 UTC, chin8628 commented on src/main/java/th/ac/kmitl/it/soa/group3/model/supplychaintradetransaction/TelephoneUniversalCommunicationModel.java
> +    public TelephoneUniversalCommunicationModel(String phoneNumber) {
OK ครับ เดี๋ยวขอแก้ก่อนนะครับ

2018-02-25 14:10 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group3/model/supplychaintradetransaction/TelephoneUniversalCommunicationModel.java
> +    public TelephoneUniversalCommunicationModel(String phoneNumber) {
หลายอย่างมัน valid นะ วันนี้ว่าแค่นี้ แต่ถ้าอนาคตมี change มา แล้ว pattern ที่เราใช้ในหลายๆส่วนที่คล้ายกัน มันไม่เหมือนกัน จะมีปัญหาในการ maintain ในอนาคต

การ enforce pattern บางทีมันก็ over-engineering นั่นแหละ แต่เรายัง prefer ให้มัน treat แบบเดียวกันมากกว่า

2018-02-25 14:38 UTC, chin8628 commented on src/main/java/th/ac/kmitl/it/soa/group3/model/supplychaintradetransaction/TelephoneUniversalCommunicationModel.java
> +public class TelephoneUniversalCommunicationModel {
ตรงนี้มีคำแนะนำเพิ่มเติมไหมครับ ยังไม่เก็ตเรื่องการ binding ชื่อครับ

2018-02-25 14:47 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group3/model/supplychaintradetransaction/TelephoneUniversalCommunicationModel.java
> +public class TelephoneUniversalCommunicationModel {
รอเรียนคาบหน้า 55 ยังไม่ถึง มันเป็นเรื่องการใช้ Design Pattern เพื่อสร้างเป็น Code Architecture

2018-02-25 15:23 UTC, chin8628 commented on src/main/java/th/ac/kmitl/it/soa/group3/model/supplychaintradetransaction/TelephoneUniversalCommunicationModel.java
> +public class TelephoneUniversalCommunicationModel {
@champillon ผมพึ่งสังเกต คลาสที่พี่พูดถึงมันไม่มีแล้วนะครับ ผมแก้ชื่อไปนานแล้ว ส่วนเรื่อง binding พี่หมายถึงอันนี้ปะครับ https://docs.oracle.com/javase/7/docs/api/javax/naming/Binding.html

2018-02-25 15:24 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group3/model/supplychaintradetransaction/TelephoneUniversalCommunicationModel.java
> +public class TelephoneUniversalCommunicationModel {
ไม่ใช่จร้าาาาา Binding แปลว่าไป ผูกจร้าาาา ไม่ใช่ศัพท์เทคนิค

2018-02-25 15:26 UTC, chin8628 commented on src/main/java/th/ac/kmitl/it/soa/group3/model/supplychaintradetransaction/TelephoneUniversalCommunicationModel.java
> +public class TelephoneUniversalCommunicationModel {
ผมเห็นว่ามันช่วยผูกชื่อเหมือนกัน 55555 เพราะมันนี้มันตั้งชื่อให้ class ที่เราใช้อยู่ได้ครับ

2018-02-25 15:26 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group3/model/supplychaintradetransaction/TelephoneUniversalCommunicationModel.java
> +public class TelephoneUniversalCommunicationModel {
555555 ไม่ใช่ๆ อธิบายในนี้จะงง ต้องเจอหน้ากันแล้วเล่าถึงเข้าใจ

2018-02-25 15:34 UTC, chin8628 commented on src/main/java/th/ac/kmitl/it/soa/group3/model/supplychaintradetransaction/TelephoneUniversalCommunicationModel.java
> +public class TelephoneUniversalCommunicationModel {
รู้สึกว่าต้องหาวิธีให้ได้ก่อนเจอพี่ครับ เดี๋ยวลอง implement proxy pattern ลงไปก่อนครับ 5555

2018-03-02 08:27 UTC, chin8628 commented
@champillon อันนี้ขอ Approve ก่อนได้ไหมครับ แล้วเดี๋ยวค่อย refactor หลังเรียนอีกรอบครับ

2018-03-02 14:51 UTC, merged

2018-03-02 14:54 UTC, champillon commented
คะแนนครับ 2.5 คะแนน x 2 Promotion => 5 คะแนน
5.1 การ design เป็น components เพื่อทำให้คนอื่นทำงานร่วมกันต่อได้ง่าย => 1 คะแนน
5.2 คุณภาพของการตั้งชื่อตัวแปร, ฟังก์ชั่น และความเรียบร้อยของ code => 0.5 คะแนน (หักค่าตั้งชื่อยาวๆไปนะ)
5.3 ความยากเชิงเทคนิคที่นำมาประยุกต์ใช้ เช่น แปลง XML Schema เป็น Java code => 0 คะแนน
5.4 รายละเอียดการตั้งชื่อใน PR name และ commit log รวมทั้งรายละเอียดที่บรรยายใน issue ของ PR นั้นๆ => 0.75 คะแนน
5.5 ความสอดคล้องกันกับ PR อื่นๆของทีม ที่ทำงานร่วมกันได้ดี => 0.25 คะแนน