[Update] Add API endpoint to ExchangedDocumentController and create wrapper with unit test
it-kmitl-2018/group3-backend pull request #54
Opened 2018-03-06 05:28 UTC by wirunpong-j

[Add] ExchangedDocWrapper with unit test
[Update] ExchangedDocumentController to post method 
[Update] ExchangedDocumentControllerTest to post method

ใช้ wrapper เพื่อลดความซับซ้อนในการสร้าง model

2018-03-06 10:28 UTC, champillon requested changes
ฝากแก้ด้วยครับ

2018-03-06 10:28 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group3/controller/ExchangedDocumentController.java
> +    @PostMapping(value = "/exchangeddoc")
ทำไมไม่ชื่อ /tax_invoice หล่ะ???

2018-03-06 10:28 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group3/controller/ExchangedDocumentController.java
>  public class ExchangedDocumentController {
ทำไมใช้ชื่อ ExchangedDocumentController หล่ะ

2018-03-06 10:37 UTC, wirunpong-j commented
@champillon แก้ละค้าบบบบบบ

2018-03-07 04:34 UTC, champillon requested changes
ฝากแก้ไขด้วยครับ

2018-03-07 04:34 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group3/wrapper/ExchangedDocWrapper.java
> +public class ExchangedDocWrapper {
ถ้าอันนั้นเป็น TaxInvoiceController อันนี้ก็ควรเป็น TaxInvoiceForm แล้วค่อยโยน TaxInvoiceForm เข้าไปใน ExchangedDocumentWrapper(TaxInvoiceForm) อะไรแบบนี้ แล้วค่อยแปลงเป็น XML

แบ่ง package เป็น controllers, wrappers, forms ก็ได้นะครับ จะได้แยกส่วนกันไปเลย

2018-03-07 06:16 UTC, wirunpong-j commented on src/main/java/th/ac/kmitl/it/soa/group3/wrapper/ExchangedDocWrapper.java
> +public class ExchangedDocWrapper {
ไม่เข้าใจว่า forms คืออะไรครับ

2018-03-07 08:23 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group3/wrapper/ExchangedDocWrapper.java
> +public class ExchangedDocWrapper {
ส่วนใหญ่ เวลาเรารับ input จากหน้าบ้าน เราจะใช้ suffix ว่า Form (เหมือน HTML form อะไรแบบนั้น) เพราะส่วนใหญ่ data structure ที่รับมาจากหน้าบ้าน จะไม่ตรงกับ data structure ที่เราจะไปใช้ในหลังบ้าน เราเลยต้อง transform หรือ wrap มันนั่นเอง

แต่ suffix ว่า Form เปลี่ยนเป็นอย่างอื่นก็ได้นะ อันนี้แค่ standard ที่ office เราใช้

2018-03-07 09:17 UTC, wirunpong-j commented on src/main/java/th/ac/kmitl/it/soa/group3/wrapper/ExchangedDocWrapper.java
> +public class ExchangedDocWrapper {
ตอนนี้มองว่าทำเป็นวงรอบ agile ครับ เลยมองว่าตอนนี้เรารับแค่ model เดียวเพื่อ export ข้อมูล ยังไม่ได้คิดเผื่อกรณีมีหลาย model ต่อ 1 api ครับ เพราะถ้าเดียวรอบต่อไปมีต้องเพิ่ม model อื่นเข้ามาก็จะขอค่อยทำ form เพิ่มตอนนั้นได้ไหมครับ

- @chin8628 ตอบครับ พอดีผมไม่ได้อยู่หน้าคอมตัวเองครับ บอกไว้เผื่อพี่งงว่าประโยคมันเหมือนคนละคน 55555

2018-03-07 09:27 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group3/wrapper/ExchangedDocWrapper.java
> +public class ExchangedDocWrapper {
ของนาย จะเป็น 1 model - 1 api -> 1 wrapper ปร่ะ??

2018-03-07 10:15 UTC, wirunpong-j commented on src/main/java/th/ac/kmitl/it/soa/group3/wrapper/ExchangedDocWrapper.java
> +public class ExchangedDocWrapper {
ถ้าตามเอกสารโครงสร้าง (หน้า 11) ผมจะแบ่ง wrapper เป็น 3 ส่วนครับ
1. Exchanged Document Context = 1 model
2. Exchanged Document = 1 model
3. Supply Chain Trade Transaction โดยในส่วนที่ 3 จะมี wrapper ย่อยอีกครับ เนื่องจากมี model เยอะมากกกกกกก

2018-03-07 10:19 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group3/wrapper/ExchangedDocWrapper.java
> +public class ExchangedDocWrapper {
เราแค่กำลังคิดว่า จาก front-end นายจะรับเป็น ETDAModel เลย หรือจะรับเป็น Wrapper ที่ wrap ชื่อ field ให้เข้าใจง่ายแล้ว

2018-03-07 10:21 UTC, wirunpong-j commented on src/main/java/th/ac/kmitl/it/soa/group3/wrapper/ExchangedDocWrapper.java
> +public class ExchangedDocWrapper {
คือของที่ front-end จะส่งมาเป็น json ที่มีชื่อตัวแปรตรงกับ wrapper ครับ แล้วมันจะ map เป็น class ของ wrapper ให้ แล้วก็คาย xml ให้อะครับ

2018-03-07 10:23 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group3/wrapper/ExchangedDocWrapper.java
> +public class ExchangedDocWrapper {
นั่นแหละ เราว่า json ที่ชื่อตรงกับ wrapper แต่ชื่อ variable ใน wrapper ของนายเข้าใจยาก มันจะ maintain ยาก

เราเลยเสนอว่า json bind กับ Pojo อันนึง ที่ใช้ Suffix ว่า Form แล้วค่อยเอา Form ไป Wrap ใส่ Wrapper เพื่อสร้าง XML แบบนี้จะทำให้ชื่อตัวแปร maintain ง่ายกว่า

2018-03-07 10:27 UTC, wirunpong-j commented on src/main/java/th/ac/kmitl/it/soa/group3/wrapper/ExchangedDocWrapper.java
> +public class ExchangedDocWrapper {
อ่อววววววววววว์ โอเคครับ เดะลองดูนะครับ พอเข้าใจละ

2018-03-07 10:46 UTC, wirunpong-j commented on src/main/java/th/ac/kmitl/it/soa/group3/wrapper/ExchangedDocWrapper.java
> +public class ExchangedDocWrapper {
@champillon แก้ละครับ สาธุ 99

2018-03-08 03:28 UTC, champillon requested changes
มันทำให้ code เข้าใจได้ง่ายกว่านี้อีกอ่ะ อย่างงี้ Wrapper ยังดูไม่ค่อยมีประโยชน์เลย

2018-03-08 03:28 UTC, champillon commented on src/main/java/th/ac/kmitl/it/soa/group3/forms/TaxInvoiceForm.java
> +public class TaxInvoiceForm {
นี่จะให้หน้าบ้านส่ง Field แบบนี้มาทั้งหมดจริงๆหรอ?
อย่าง creationDateTime มันควรจะ Stamp ที่ฝั่ง Server มากกว่า

2018-03-08 06:26 UTC, wirunpong-j commented on src/main/java/th/ac/kmitl/it/soa/group3/forms/TaxInvoiceForm.java
> +public class TaxInvoiceForm {
@champillon แก้แล้วครับ

2018-03-08 06:27 UTC, champillon approved these changes
LGTM ก็ได้

2018-03-10 05:24 UTC, wirunpong-j commented
@champillon พี่ค้าบ จะ 3 วันแล้วยัง approve ไม่ครบเลยครับ

2018-03-11 03:27 UTC, merged

2018-03-11 03:28 UTC, champillon commented
คะแนนครับ 4.25 คะแนน
5.1 การ design เป็น components เพื่อทำให้คนอื่นทำงานร่วมกันต่อได้ง่าย => 1 คะแนน
5.2 คุณภาพของการตั้งชื่อตัวแปร, ฟังก์ชั่น และความเรียบร้อยของ code => 0.5 คะแนน
5.3 ความยากเชิงเทคนิคที่นำมาประยุกต์ใช้ เช่น แปลง XML Schema เป็น Java code => 1 คะแนน
5.4 รายละเอียดการตั้งชื่อใน PR name และ commit log รวมทั้งรายละเอียดที่บรรยายใน issue ของ PR นั้นๆ => 0.75 คะแนน
5.5 ความสอดคล้องกันกับ PR อื่นๆของทีม ที่ทำงานร่วมกันได้ดี => 1 คะแนน