Crate Full Json Export from existing models
it-kmitl-2018/group3-backend pull request #74
Opened 2018-05-13 10:07 UTC by patcharapon-j

For issue #73

2018-05-13 11:57 UTC, champillon reviewed
data test ย้ายไปอยู่ใน package mocks มั้ย เพราะ test จะได้ clean ขึ้น

2018-05-13 12:06 UTC, patcharapon-j commented
@champillon ไม่เข้าใจที่ให้ย้าย Data Test ไปอยุ่ใน Package Mocks ครับผม หมายถึงยังไงหรอครับ?

2018-05-13 16:19 UTC, keattiwut requested changes
แก้ชื่อ class หน่อย มันเป็น converter หรือ แค่ data transfer object 

ส่วนเรื่องที่ ให้ move mock ไป ที่อื่นคือ เวลาน้องเอามารวมใน class test มันดูรก แยกไปเป็นอีก class เช่น .....Mock จะได้สะดวกเวลามาอ่าน

2018-05-14 04:30 UTC, champillon commented
ตามที่ @keattiwut พูดเลย

2018-05-14 09:12 UTC, patcharapon-j commented
@keattiwut @champillon แก้ไขแล้วครับผม

2018-05-14 09:40 UTC, keattiwut approved these changes

2018-05-15 07:47 UTC, merged

2018-05-20 14:51 UTC, champillon commented
2 คะแนน